### ISSUE TITLE
[Icon Request] Qubes OS (A Xen/Linux Distribution)

### ISSUE THREAD

**Issue by Cyanide-1** [darkomarko42/Marwaita-Icons#1]
**Icon Name**: distributor-logo-qubes
**Description**: "A reasonably secure operating system"
**Website**: https://www.qubes-os.org/
**Reference Pictures**: https://www.qubes-os.org/doc/visual-style-guide/#logos
![qubes-logo](https://github.com/darkomarko42/Marwaita-Icons/assets/136278181/b9ea7b29-72a4-485f-964f-5444ba80acd6)
![qubes-logo-2000x-2150x](https://github.com/darkomarko42/Marwaita-Icons/assets/136278181/3fa5e220-14fb-4984-b9e4-b10850e265f3)

**Comment by darkomarko42** [comment]
thats already on the package.
named "distributor-logo-qubes.svg"
